### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'com.anychart.AnyChartView$JsListener com.anychart.AnyChartView.getJsListener()' on a null object reference

### ISSUE THREAD

**Issue by diaconori** [AnyChart/AnyChart-Android#145]
I noticed that this issue was closed by another developer, but the thread did not address a solution for this issue. As such, I've recreated it as listed below:

--------

**Build.Gradle (:app):**

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.XXXXXX.XXXX"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'com.github.AnyChart:AnyChart-Android:1.1.2'
    implementation 'com.android.support:multidex:1.0.3'
}
```

--------------------

**Build.Gradle (project):**
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.0'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
----------------------------

**fragment_home.xml:**

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".home.HomeFragment">

    <com.anychart.AnyChartView android:id="@+id/any_chart_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content" />

</FrameLayout>

-------------------

**MainActivity.java:**

 ```
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        AnyChartView chart = findViewById(R.id.any_chart_view);
        Pie pie = AnyChart.pie();

        List<DataEntry> data = new ArrayList<>();
        data.add(new ValueDataEntry("John", 10000));
        data.add(new ValueDataEntry("Jake", 12000));
        data.add(new ValueDataEntry("Peter", 18000));

        chart.setChart(pie);

        BottomNavigationView bottomNavigationView = findViewById(R.id.bottom_navigation);
        bottomNavigationView.setOnNavigationItemSelectedListener(navListener);
        getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container, new HomeFragment()).commit();
    }
```

-------------

**Exception:**
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.anychart.AnyChartView$JsListener com.anychart.AnyChartView.getJsListener()' on a null object reference
        at com.anychart.APIlib.addJSLine(APIlib.java:27)
        at com.anychart.charts.Pie.<init>(Pie.java:34)
        at com.anychart.AnyChart.pie(AnyChart.java:130)

NONE of the StackOverflow answers have a solution to this fix. It throws the NullPointerException at:
`        Pie pie = AnyChart.pie();`

![image](https://user-images.githubusercontent.com/37276987/75543644-95647c80-5a22-11ea-8554-c06a7aba884e.png)

**Comment by Shestac92** [comment]
@diaconori 
Thank you for the report!
We will investigate the issue and let you know about the result.

**Comment by EmeseReka** [comment]
I have the same error. Is there progress in resolving this?

**Comment by Shestac92** [comment]
@EmeseReka 
Unfortunately, we didn't succeed to reproduce the issue.
Can you provide details on your case?

**Comment by buuzuu** [comment]
I am also getting this error only when I am inflating a custom view using alert dialog but when I am using it my main activity ,it's working fine.

**Comment by diaconori** [comment]
This error occured when implementing this in a fragment's onViewCreated method. After searching for a long time, I noticed that if I implemented this in onActivityCreated, I did not experience any problems. Issue closed.

**Comment by vaidik1011** [comment]
i am also having the same issue whenever i change activity and come back to main activity where anychart is. it crashes 

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.anychart.core.Chart.getJsBase()' on a null object reference
        at com.anychart.AnyChartView$4.onPageFinished(AnyChartView.java:157)
        at oB0.a(chromium-TrichromeWebViewGoogle6432.aab-stable-530414134:11)
        at la.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-530414134:328)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8333)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)`

**Comment by SSTechSystem** [comment]
This issue is still there. Does anyone have any clue? Or a resolution for this?
